// Generated by Tools/reference_rl_nn.py — do not edit.
// Python reference values for the seeded algorithms of worlds 5, 6 and 10.
import Foundation

enum GoldenRLValues {
    static let mazeOutcomes: [String] = ["treat", "treat", "treat", "treat", "treat", "treat"]
    static let mazeEpisodeLengths: [Int] = [16, 12, 7, 25, 24, 16]
    static let mazeStartQ: [Double] = [-0.0781425, -0.07200000000000001, -0.119225, -0.13610624999999998]
    static let mazeGreedyOutcome = "treat"
    static let mazeGreedyPath: [[Int]] = [[0, 0], [1, 0], [2, 0], [3, 0], [3, 1], [3, 2], [3, 3]]
    static let mazeRandomDraws: [Double] = [0.6227655366461097]
    static let networkFirstWeights: [Double] = [-0.18117112642570565, 0.5988009562779071, 0.7023603182656251, -0.5482961338594375]
    static let networkInitialLoss: Double = 0.7158311958930906
    static let networkFirstEpochLoss: Double = 0.7158311958930906
    static let networkLossAfterTenEpochs: Double = 0.5663754575658729
    static let networkCorrectAfterTenEpochs: Int = 11
    static let storyVariantsSeed42: [Int] = [1, 1, 0]
    static let splitMixSeed1: [UInt64] = [10451216379200822465, 13757245211066428519, 17911839290282890590]
}
