// GENERATED by Tools/reference_model.py — do not edit by hand.
// Golden values shared between the Python reference model and AICatCore.
import Foundation

enum GoldenValues {
    struct Growth { let xp: Double; let normalized: Double; let stage: Int; let bodyLength: Double; let headRadiusRatio: Double; let legLength: Double; let earScale: Double; let tailLength: Double; let eyeRadiusRatio: Double }
    static let growth: [Growth] = [
        Growth(xp: 0.0, normalized: 0.0, stage: 0, bodyLength: 0.23, headRadiusRatio: 0.42, legLength: 0.062, earScale: 1.3, tailLength: 0.125, eyeRadiusRatio: 0.28),
        Growth(xp: 100.0, normalized: 0.013888888888888888, stage: 0, bodyLength: 0.23017773705418382, headRadiusRatio: 0.41993119855967076, legLength: 0.062070521476337445, earScale: 1.299827996399177, tailLength: 0.12512900270061728, eyeRadiusRatio: 0.27994266546639235),
        Growth(xp: 250.0, normalized: 0.034722222222222224, stage: 0, bodyLength: 0.2310952838327332, headRadiusRatio: 0.4195760191615226, legLength: 0.0624345803594393, earScale: 1.2989400479038067, tailLength: 0.12579496407214505, eyeRadiusRatio: 0.27964668263460224),
        Growth(xp: 500.0, normalized: 0.06944444444444445, stage: 0, bodyLength: 0.23427731695816187, headRadiusRatio: 0.41834426440329214, legLength: 0.06369712898662551, earScale: 1.2958606610082304, tailLength: 0.12810450424382716, eyeRadiusRatio: 0.27862022033607686),
        Growth(xp: 719.0, normalized: 0.09986111111111111, stage: 0, bodyLength: 0.23865676435351296, headRadiusRatio: 0.41664899444380143, legLength: 0.06543478069510353, earScale: 1.2916224861095036, tailLength: 0.1312831354178723, eyeRadiusRatio: 0.2772074953698346),
        Growth(xp: 720.0, normalized: 0.1, stage: 1, bodyLength: 0.23868, headRadiusRatio: 0.41664, legLength: 0.065444, earScale: 1.2916, tailLength: 0.1313, eyeRadiusRatio: 0.2772),
        Growth(xp: 1000.0, normalized: 0.1388888888888889, stage: 1, bodyLength: 0.24627872085048014, headRadiusRatio: 0.4136985596707819, legLength: 0.06845897633744856, earScale: 1.2842463991769548, tailLength: 0.13681520061728394, eyeRadiusRatio: 0.2747487997256516),
        Growth(xp: 1500.0, normalized: 0.20833333333333334, stage: 2, bodyLength: 0.2647583912037037, headRadiusRatio: 0.4065451388888889, legLength: 0.07579123263888889, earScale: 1.2663628472222221, tailLength: 0.15022786458333334, eyeRadiusRatio: 0.2687876157407408),
        Growth(xp: 2000.0, normalized: 0.2777777777777778, stage: 2, bodyLength: 0.28847050754458164, headRadiusRatio: 0.3973662551440329, legLength: 0.08519958847736626, earScale: 1.2434156378600822, tailLength: 0.1674382716049383, eyeRadiusRatio: 0.2611385459533608),
        Growth(xp: 3000.0, normalized: 0.4166666666666667, stage: 4, bodyLength: 0.3466087962962963, headRadiusRatio: 0.3748611111111111, legLength: 0.10826736111111111, earScale: 1.1871527777777777, tailLength: 0.20963541666666669, eyeRadiusRatio: 0.24238425925925927),
        Growth(xp: 3600.0, normalized: 0.5, stage: 5, bodyLength: 0.385, headRadiusRatio: 0.36, legLength: 0.1235, earScale: 1.15, tailLength: 0.2375, eyeRadiusRatio: 0.23),
        Growth(xp: 4000.0, normalized: 0.5555555555555556, stage: 5, bodyLength: 0.41072702331961597, headRadiusRatio: 0.35004115226337446, legLength: 0.13370781893004116, earScale: 1.1251028806584362, tailLength: 0.25617283950617287, eyeRadiusRatio: 0.22170096021947874),
        Growth(xp: 4500.0, normalized: 0.625, stage: 6, bodyLength: 0.44191406250000004, headRadiusRatio: 0.33796875, legLength: 0.14608203125, earScale: 1.094921875, tailLength: 0.27880859375, eyeRadiusRatio: 0.211640625),
        Growth(xp: 5000.0, normalized: 0.6944444444444444, stage: 6, bodyLength: 0.47085862482853225, headRadiusRatio: 0.32676440329218104, legLength: 0.1575664866255144, earScale: 1.0669110082304527, tailLength: 0.2998167438271605, eyeRadiusRatio: 0.20230366941015088),
        Growth(xp: 6000.0, normalized: 0.8333333333333334, stage: 8, bodyLength: 0.5170370370370372, headRadiusRatio: 0.3088888888888889, legLength: 0.1758888888888889, earScale: 1.0222222222222221, tailLength: 0.33333333333333337, eyeRadiusRatio: 0.1874074074074074),
        Growth(xp: 7000.0, normalized: 0.9722222222222222, stage: 9, bodyLength: 0.5392956961591221, headRadiusRatio: 0.30027263374485597, legLength: 0.18472055041152263, earScale: 1.00068158436214, tailLength: 0.349488811728395, eyeRadiusRatio: 0.18022719478737997),
        Growth(xp: 7199.0, normalized: 0.9998611111111111, stage: 9, bodyLength: 0.5399999820618463, headRadiusRatio: 0.3000000069438014, legLength: 0.18499999288260352, earScale: 1.0000000173595036, tailLength: 0.34999998698037227, eyeRadiusRatio: 0.1800000057865012),
        Growth(xp: 7200.0, normalized: 1.0, stage: 10, bodyLength: 0.54, headRadiusRatio: 0.3, legLength: 0.185, earScale: 1.0, tailLength: 0.35, eyeRadiusRatio: 0.18),
        Growth(xp: 8000.0, normalized: 1.0, stage: 10, bodyLength: 0.54, headRadiusRatio: 0.3, legLength: 0.185, earScale: 1.0, tailLength: 0.35, eyeRadiusRatio: 0.18),
        Growth(xp: 9000.0, normalized: 1.0, stage: 10, bodyLength: 0.54, headRadiusRatio: 0.3, legLength: 0.185, earScale: 1.0, tailLength: 0.35, eyeRadiusRatio: 0.18),
        Growth(xp: 9500.0, normalized: 1.0, stage: 10, bodyLength: 0.54, headRadiusRatio: 0.3, legLength: 0.185, earScale: 1.0, tailLength: 0.35, eyeRadiusRatio: 0.18),
    ]
    static let xpForStage: [Double] = [0.0, 720.0, 1440.0, 2160.0, 2880.0, 3600.0, 4320.0, 5040.0, 5760.0, 6480.0, 7200.0]

    static let difficultyInputs: [Double] = [1.0, 1.0, 0.5, 0.25, 0.9, 0.75, 0.6, 1.0, 1.0, 1.0, 0.0]
    static let difficultyApprenticeTrace: [Double] = [0.4875, 0.525, 0.48750000000000004, 0.41250000000000003, 0.43500000000000005, 0.43500000000000005, 0.41250000000000003, 0.45, 0.4875, 0.525, 0.41250000000000003]
    static let itemCounts: [(lo: Int, hi: Int, d: Double, n: Int)] = [(lo: 4, hi: 12, d: 0.0, n: 4), (lo: 4, hi: 12, d: 0.5, n: 8), (lo: 4, hi: 12, d: 1.0, n: 12), (lo: 6, hi: 9, d: 0.33, n: 7), (lo: 3, hi: 10, d: 0.5, n: 7), (lo: 5, hi: 5, d: 0.9, n: 5)]

    static let xpCases: [(tier: Int, accuracy: Double, xp: Int, stars: Int)] = [(tier: 1, accuracy: 1.0, xp: 100, stars: 3), (tier: 1, accuracy: 0.5, xp: 50, stars: 1), (tier: 1, accuracy: 0.0, xp: 50, stars: 1), (tier: 2, accuracy: 0.8, xp: 160, stars: 2), (tier: 3, accuracy: 0.95, xp: 285, stars: 3), (tier: 3, accuracy: 1.0, xp: 300, stars: 3), (tier: 2, accuracy: 0.749, xp: 150, stars: 1), (tier: 1, accuracy: 0.8, xp: 80, stars: 2)]

    static let entropyCases: [(labels: [String], entropy: Double)] = [(labels: ["a", "b"], entropy: 1.0), (labels: ["a", "a", "a"], entropy: -0.0), (labels: ["a", "a", "b", "c"], entropy: 1.5), (labels: ["x"], entropy: -0.0), (labels: ["a", "b", "c", "d"], entropy: 2.0), (labels: [], entropy: 0.0)]
    static let informationGainColor: Double = 1.0
    static let informationGainShape: Double = 0.0

    static let knnExamples: [(features: [Double], label: String)] = [(features: [0.3, 0.9, 0.2], label: "cat"), (features: [0.35, 0.85, 0.25], label: "cat"), (features: [0.28, 0.95, 0.15], label: "cat"), (features: [0.6, 0.4, 0.6], label: "dog"), (features: [0.7, 0.35, 0.65], label: "dog"), (features: [0.55, 0.45, 0.55], label: "dog"), (features: [0.1, 0.0, 0.9], label: "bird"), (features: [0.12, 0.05, 0.95], label: "bird"), (features: [0.08, 0.02, 0.85], label: "bird")]
    static let knnQueries: [(features: [Double], label: String)] = [(features: [0.31, 0.88, 0.22], label: "cat"), (features: [0.65, 0.38, 0.62], label: "dog"), (features: [0.11, 0.03, 0.9], label: "bird"), (features: [0.45, 0.6, 0.4], label: "dog"), (features: [0.2, 0.5, 0.55], label: "dog")]
}
