# -*- coding: utf-8 -*-
"""Single source of truth for every user-facing string of AI CAT (en / es).

Run `python3 Tools/gen_strings.py` after editing: it regenerates
AICat/Resources/Localizable.xcstrings and AICat/Resources/InfoPlist.xcstrings.
Keys are referenced from Swift through `L10n.string("key")` (app) and
`TextKey("key")` (AICatCore). `Tools/validate_project.py` checks that every
referenced key exists here and has both languages.
"""

STRINGS = {
    # ---- app / common -------------------------------------------------------
    "app.name": ("AI CAT", "AI CAT"),
    "app.tagline": ("Learn AI with a curious kitten", "Aprende IA con un gatito curioso"),
    "common.continue": ("Continue", "Continuar"),
    "common.back": ("Back", "Atrás"),
    "common.play": ("Play", "Jugar"),
    "common.next": ("Next", "Siguiente"),
    "common.retry": ("Try again", "Intentar de nuevo"),
    "common.done": ("Done", "Listo"),
    "common.close": ("Close", "Cerrar"),
    "common.cancel": ("Cancel", "Cancelar"),
    "common.ok": ("OK", "OK"),
    "common.yes": ("Yes", "Sí"),
    "common.no": ("No", "No"),
    "common.loading": ("Loading…", "Cargando…"),
    "common.coming_soon": ("Coming soon", "Próximamente"),
    "common.locked": ("Locked", "Bloqueado"),
    "common.level": ("Level", "Nivel"),
    "common.xp": ("XP", "XP"),
    "common.stage": ("Stage", "Etapa"),
    "common.hint": ("Hint", "Pista"),
    "common.skip": ("Skip", "Saltar"),
    "common.settings": ("Settings", "Ajustes"),
    "common.language": ("Language", "Idioma"),
    "common.english": ("English", "Inglés"),
    "common.spanish": ("Spanish", "Español"),
}

INFOPLIST = {
    "CFBundleDisplayName": ("AI CAT", "AI CAT"),
    "CFBundleName": ("AI CAT", "AI CAT"),
}

# ---- curriculum ------------------------------------------------------------
STRINGS.update({
    "ageband.explorer.title": ("Explorer (6–7)", "Explorador (6–7)"),
    "ageband.explorer.description": ("Short sentences, AI CAT reads everything aloud and helps right away.", "Frases cortas, AI CAT lee todo en voz alta y ayuda enseguida."),
    "ageband.apprentice.title": ("Apprentice (8–10)", "Aprendiz (8–10)"),
    "ageband.apprentice.description": ("More items, hints on request, numbers and bars.", "Más elementos, pistas a pedido, números y barras."),
    "ageband.master.title": ("Master (11–12)", "Maestro (11–12)"),
    "ageband.master.description": ("Bigger challenges, a gentle timer and the real numbers behind the AI.", "Retos más grandes, un cronómetro suave y los números reales detrás de la IA."),

    "bigidea.perception": ("Perception", "Percepción"),
    "bigidea.representation": ("Representation and reasoning", "Representación y razonamiento"),
    "bigidea.learning": ("Learning", "Aprendizaje"),
    "bigidea.natural_interaction": ("Natural interaction", "Interacción natural"),
    "bigidea.societal_impact": ("Societal impact", "Impacto social"),

    "knowledge.collar": ("Learner's collar", "Collar de aprendiz"),
    "knowledge.bandana": ("Data bandana", "Pañoleta de datos"),
    "knowledge.glasses": ("Classifier glasses", "Lentes clasificadores"),
    "knowledge.backpack": ("Algorithm backpack", "Mochila de algoritmos"),
    "knowledge.compass": ("Explorer's compass", "Brújula exploradora"),
    "knowledge.headband": ("Neuron headband", "Diadema de neuronas"),
    "knowledge.goggles": ("Vision goggles", "Gafas de visión"),
    "knowledge.headphones": ("Language headphones", "Audífonos de lenguaje"),
    "knowledge.badge": ("Fairness badge", "Insignia de justicia"),
    "knowledge.graduation_cap": ("Graduation cap", "Birrete de graduación"),

    # scenario 1
    "scenario.1.title": ("Pattern Garden", "Jardín de Patrones"),
    "scenario.1.subtitle": ("What is AI? Patterns and rules", "¿Qué es la IA? Patrones y reglas"),
    "scenario.1.concept": ("A computer can follow a rule you give it, or learn the rule from your examples. That second thing is AI!", "Una computadora puede seguir una regla que le das, o aprender la regla con tus ejemplos. ¡Eso segundo es IA!"),
    "scenario.1.intro": ("Welcome to my garden! Sort the fruits into the baskets and watch me learn the pattern.", "¡Bienvenido a mi jardín! Acomoda las frutas en las canastas y mira cómo aprendo el patrón."),
    "challenge.s1.c1.title": ("Red or green?", "¿Roja o verde?"),
    "challenge.s1.c1.goal": ("Put each fruit in the basket of its colour.", "Pon cada fruta en la canasta de su color."),
    "challenge.s1.c1.concept": ("A rule tells us what to do. Follow it and I will watch.", "Una regla nos dice qué hacer. Síguela y yo observo."),
    "challenge.s1.c2.title": ("The secret pattern", "El patrón secreto"),
    "challenge.s1.c2.goal": ("Nobody told us the rule. Try, watch the glow, and find the pattern.", "Nadie nos dijo la regla. Prueba, mira el brillo y descubre el patrón."),
    "challenge.s1.c2.concept": ("Learning means finding the pattern from examples.", "Aprender es encontrar el patrón a partir de ejemplos."),
    "challenge.s1.c3.title": ("Two clues at once", "Dos pistas a la vez"),
    "challenge.s1.c3.goal": ("Only the fruits with BOTH clues go to basket 1.", "Solo las frutas con las DOS pistas van a la canasta 1."),
    "challenge.s1.c3.concept": ("Rules can combine clues. Harder patterns need more examples.", "Las reglas pueden combinar pistas. Los patrones difíciles necesitan más ejemplos."),
    "challenge.s1.c4.title": ("Master gardener", "Maestro del jardín"),
    "challenge.s1.c4.goal": ("More fruits, more clues, fewer hints. Find the pattern and let me finish.", "Más frutas, más pistas, menos ayuda. Encuentra el patrón y déjame terminar."),
    "challenge.s1.c4.concept": ("AI learns from your examples, so good examples matter.", "La IA aprende de tus ejemplos, así que los buenos ejemplos importan."),

    # scenario 2
    "scenario.2.title": ("Data Library", "Biblioteca de Datos"),
    "scenario.2.subtitle": ("Data, labels and quality", "Datos, etiquetas y calidad"),
    "scenario.2.concept": ("AI learns from data. Labels tell it what each example is. More and better data means better guesses.", "La IA aprende de datos. Las etiquetas le dicen qué es cada ejemplo. Más y mejores datos, mejores respuestas."),
    "scenario.2.intro": ("This library is full of animal cards. Label them and I will learn to tell them apart!", "Esta biblioteca está llena de tarjetas de animales. ¡Etiquétalas y aprenderé a distinguirlos!"),
    "challenge.s2.c1.title": ("Cat or dog?", "¿Gato o perro?"),
    "challenge.s2.c1.goal": ("Label each card and watch my accuracy meter rise.", "Etiqueta cada tarjeta y mira cómo sube mi medidor."),
    "challenge.s2.c1.concept": ("Each label is one piece of data for me.", "Cada etiqueta es un dato para mí."),
    "challenge.s2.c2.title": ("Three animals", "Tres animales"),
    "challenge.s2.c2.goal": ("Now birds too. Label them all so I can guess the hidden cards.", "Ahora también aves. Etiqueta todas para que adivine las tarjetas ocultas."),
    "challenge.s2.c2.concept": ("More kinds need more examples of each kind.", "Más tipos necesitan más ejemplos de cada tipo."),
    "challenge.s2.c3.title": ("The sneaky mouse", "El ratón travieso"),
    "challenge.s2.c3.goal": ("A mouse mixed up a label! Find it and fix it.", "¡Un ratón cambió una etiqueta! Encuéntrala y arréglala."),
    "challenge.s2.c3.concept": ("Wrong data makes AI guess wrong. Quality matters.", "Los datos malos hacen que la IA se equivoque. La calidad importa."),
    "challenge.s2.c4.title": ("Master librarian", "Maestro de la biblioteca"),
    "challenge.s2.c4.goal": ("Noisy cards and two mixed-up labels. Build a clean dataset.", "Tarjetas confusas y dos etiquetas cambiadas. Construye un conjunto de datos limpio."),
    "challenge.s2.c4.concept": ("Clean, balanced data is the secret of good AI.", "Datos limpios y balanceados son el secreto de una buena IA."),

    # scenario 3
    "scenario.3.title": ("Classifier Workshop", "Taller de Clasificación"),
    "scenario.3.subtitle": ("Training a classifier", "Entrenar un clasificador"),
    "scenario.3.concept": ("A classifier draws a line between groups. Examples on each side teach it where the line goes.", "Un clasificador traza una línea entre grupos. Los ejemplos de cada lado le enseñan dónde va la línea."),
    "scenario.3.intro": ("In my workshop we build a machine that separates things. Put examples on the board!", "En mi taller construimos una máquina que separa cosas. ¡Pon ejemplos en el tablero!"),
    "challenge.s3.c1.title": ("Big or small", "Grande o pequeño"),
    "challenge.s3.c1.goal": ("Place animals on the board by size and fluffiness.", "Coloca animales en el tablero por tamaño y pelusa."),
    "challenge.s3.c1.concept": ("Features are numbers that describe things.", "Los rasgos son números que describen cosas."),
    "challenge.s3.c2.title": ("Draw the line", "Traza la línea"),
    "challenge.s3.c2.goal": ("Move the line so each group stays on its side.", "Mueve la línea para que cada grupo quede de su lado."),
    "challenge.s3.c2.concept": ("The decision boundary separates classes.", "La frontera de decisión separa las clases."),
    "challenge.s3.c3.title": ("Three groups", "Tres grupos"),
    "challenge.s3.c3.goal": ("Find the centres of three groups and let me classify new animals.", "Encuentra los centros de tres grupos y deja que clasifique nuevos animales."),
    "challenge.s3.c3.concept": ("Centroids are the average of each group.", "Los centroides son el promedio de cada grupo."),
    "challenge.s3.c4.title": ("Master builder", "Maestro constructor"),
    "challenge.s3.c4.goal": ("Strange animals appear. Decide if they are mistakes or a new group.", "Aparecen animales raros. Decide si son errores o un grupo nuevo."),
    "challenge.s3.c4.concept": ("Outliers can confuse a classifier.", "Los valores atípicos pueden confundir a un clasificador."),

    # scenario 4
    "scenario.4.title": ("Algorithm Trail", "Sendero de Instrucciones"),
    "scenario.4.subtitle": ("Algorithms: step by step", "Algoritmos: paso a paso"),
    "scenario.4.concept": ("An algorithm is a list of clear steps. Computers follow them exactly, even the silly ones.", "Un algoritmo es una lista de pasos claros. Las computadoras los siguen tal cual, hasta los tontos."),
    "scenario.4.intro": ("Guide me along the trail with instruction blocks. I only do exactly what you say!", "Guíame por el sendero con bloques de instrucciones. ¡Solo hago exactamente lo que dices!"),
    "challenge.s4.c1.title": ("First steps", "Primeros pasos"),
    "challenge.s4.c1.goal": ("Put the blocks in order to reach the fish.", "Ordena los bloques para llegar al pez."),
    "challenge.s4.c1.concept": ("Order matters in an algorithm.", "El orden importa en un algoritmo."),
    "challenge.s4.c2.title": ("If there is a puddle", "Si hay un charco"),
    "challenge.s4.c2.goal": ("Use an IF block to jump over puddles.", "Usa un bloque SI para saltar los charcos."),
    "challenge.s4.c2.concept": ("Conditions let a program choose.", "Las condiciones permiten que un programa elija."),
    "challenge.s4.c3.title": ("Again and again", "Otra vez y otra vez"),
    "challenge.s4.c3.goal": ("Use a REPEAT block to climb the stairs.", "Usa un bloque REPETIR para subir la escalera."),
    "challenge.s4.c3.concept": ("Loops repeat steps without rewriting them.", "Los bucles repiten pasos sin reescribirlos."),
    "challenge.s4.c4.title": ("Master explorer", "Maestro explorador"),
    "challenge.s4.c4.goal": ("Combine IF and REPEAT to cross the whole trail.", "Combina SI y REPETIR para cruzar todo el sendero."),
    "challenge.s4.c4.concept": ("Big programs are small ideas combined.", "Los programas grandes son ideas pequeñas combinadas."),

    # scenario 5
    "scenario.5.title": ("Reward Maze", "Laberinto de Recompensas"),
    "scenario.5.subtitle": ("Learning from rewards", "Aprender con recompensas"),
    "scenario.5.concept": ("Some AI learns by trying: good moves earn rewards, bad moves lose them. After many tries it finds the best path.", "Algunas IA aprenden probando: los buenos movimientos ganan recompensas, los malos las pierden. Tras muchos intentos encuentra el mejor camino."),
    "scenario.5.intro": ("I don't know this maze. Place treats and let me explore. I'll remember what worked!", "No conozco este laberinto. Pon premios y déjame explorar. ¡Recordaré lo que funcionó!"),
    "challenge.s5.c1.title": ("A treat at the end", "Un premio al final"),
    "challenge.s5.c1.goal": ("Place a treat and watch me explore until I find it.", "Pon un premio y mira cómo exploro hasta encontrarlo."),
    "challenge.s5.c1.concept": ("Rewards tell an agent what is good.", "Las recompensas le dicen al agente qué es bueno."),
    "challenge.s5.c2.title": ("Watch out for puddles", "Cuidado con los charcos"),
    "challenge.s5.c2.goal": ("Add a puddle with a penalty and see how my path changes.", "Agrega un charco con castigo y mira cómo cambia mi camino."),
    "challenge.s5.c2.concept": ("Penalties teach what to avoid.", "Los castigos enseñan qué evitar."),
    "challenge.s5.c3.title": ("Warm tiles", "Casillas tibias"),
    "challenge.s5.c3.goal": ("The tiles glow with how much I expect. Guide me with rewards.", "Las casillas brillan según lo que espero. Guíame con premios."),
    "challenge.s5.c3.concept": ("Values spread backwards from the reward.", "Los valores se propagan hacia atrás desde la recompensa."),
    "challenge.s5.c4.title": ("Master of the maze", "Maestro del laberinto"),
    "challenge.s5.c4.goal": ("Design a maze where I must learn the long, safe path.", "Diseña un laberinto donde deba aprender el camino largo y seguro."),
    "challenge.s5.c4.concept": ("Exploring and exploiting is a balance.", "Explorar y aprovechar es un equilibrio."),

    # scenario 6
    "scenario.6.title": ("Neuron Factory", "Fábrica de Neuronas"),
    "scenario.6.subtitle": ("Neural networks", "Redes neuronales"),
    "scenario.6.concept": ("Artificial neurons add up signals with weights. Many neurons together can learn almost anything.", "Las neuronas artificiales suman señales con pesos. Muchas neuronas juntas pueden aprender casi cualquier cosa."),
    "scenario.6.intro": ("Welcome to the factory where my brain is built! Turn the dials and light the right lamp.", "¡Bienvenido a la fábrica donde se construye mi cerebro! Gira las perillas y enciende la lámpara correcta."),
    "challenge.s6.c1.title": ("One neuron", "Una neurona"),
    "challenge.s6.c1.goal": ("Set two weights so the lamp lights only for the right input.", "Ajusta dos pesos para que la lámpara encienda solo con la entrada correcta."),
    "challenge.s6.c1.concept": ("A neuron multiplies, adds and decides.", "Una neurona multiplica, suma y decide."),
    "challenge.s6.c2.title": ("Three inputs", "Tres entradas"),
    "challenge.s6.c2.goal": ("More dials, same idea. Make the lamp agree with the examples.", "Más perillas, misma idea. Haz que la lámpara coincida con los ejemplos."),
    "challenge.s6.c2.concept": ("Weights say how important each input is.", "Los pesos dicen qué tan importante es cada entrada."),
    "challenge.s6.c3.title": ("Two layers", "Dos capas"),
    "challenge.s6.c3.goal": ("Connect neurons in layers to solve the tricky pattern.", "Conecta neuronas en capas para resolver el patrón difícil."),
    "challenge.s6.c3.concept": ("Layers let networks learn complex patterns.", "Las capas permiten aprender patrones complejos."),
    "challenge.s6.c4.title": ("Master engineer", "Maestro ingeniero"),
    "challenge.s6.c4.goal": ("Let the network train itself and watch the error go down.", "Deja que la red se entrene sola y mira cómo baja el error."),
    "challenge.s6.c4.concept": ("Training adjusts weights a little at a time.", "Entrenar ajusta los pesos poco a poco."),

    # scenario 7
    "scenario.7.title": ("AI CAT's Eyes", "Ojos de AI CAT"),
    "scenario.7.subtitle": ("Computer vision", "Visión por computadora"),
    "scenario.7.concept": ("To a computer an image is a grid of numbers. Finding edges and shapes in the numbers is how it sees.", "Para una computadora una imagen es una cuadrícula de números. Encontrar bordes y formas en los números es su forma de ver."),
    "scenario.7.intro": ("Let's look through my eyes! Pixels, edges, shapes… and then real objects with your camera.", "¡Miremos con mis ojos! Píxeles, bordes, formas… y luego objetos reales con tu cámara."),
    "challenge.s7.c1.title": ("Pixels", "Píxeles"),
    "challenge.s7.c1.goal": ("Zoom into an image until you see the numbers.", "Acerca una imagen hasta ver los números."),
    "challenge.s7.c1.concept": ("Images are made of pixels.", "Las imágenes están hechas de píxeles."),
    "challenge.s7.c2.title": ("Edges", "Bordes"),
    "challenge.s7.c2.goal": ("Find where colours change quickly: those are edges.", "Encuentra dónde cambian rápido los colores: esos son bordes."),
    "challenge.s7.c2.concept": ("Edges outline shapes.", "Los bordes delinean las formas."),
    "challenge.s7.c3.title": ("Shapes", "Formas"),
    "challenge.s7.c3.goal": ("Match shapes to the objects I recognise.", "Relaciona formas con los objetos que reconozco."),
    "challenge.s7.c3.concept": ("Recognition combines many small clues.", "Reconocer combina muchas pistas pequeñas."),
    "challenge.s7.c4.title": ("Master of sight", "Maestro de la vista"),
    "challenge.s7.c4.goal": ("Point the camera at real things and check my guesses.", "Apunta la cámara a cosas reales y revisa mis respuestas."),
    "challenge.s7.c4.concept": ("On-device vision keeps your photos private.", "La visión en el dispositivo mantiene tus fotos privadas."),

    # scenario 8
    "scenario.8.title": ("AI CAT's Voice", "Voz de AI CAT"),
    "scenario.8.subtitle": ("Natural language", "Lenguaje natural"),
    "scenario.8.concept": ("Language models split words into tokens and predict what comes next. That is how I talk!", "Los modelos de lenguaje parten las palabras en tokens y predicen lo que sigue. ¡Así hablo yo!"),
    "scenario.8.intro": ("On this stage we play with words: tokens, guessing the next word and, finally, talking to me!", "En este escenario jugamos con palabras: tokens, adivinar la siguiente palabra y, al final, ¡hablar conmigo!"),
    "challenge.s8.c1.title": ("Tokens", "Tokens"),
    "challenge.s8.c1.goal": ("Split sentences into pieces the way I do.", "Parte oraciones en pedazos como lo hago yo."),
    "challenge.s8.c1.concept": ("Models read tokens, not words.", "Los modelos leen tokens, no palabras."),
    "challenge.s8.c2.title": ("Guess the next word", "Adivina la siguiente palabra"),
    "challenge.s8.c2.goal": ("Pick the most likely next word and compare it with my guess.", "Elige la palabra más probable y compárala con la mía."),
    "challenge.s8.c2.concept": ("Prediction is choosing the likeliest continuation.", "Predecir es elegir la continuación más probable."),
    "challenge.s8.c3.title": ("Talk to me", "Háblame"),
    "challenge.s8.c3.goal": ("Say a sentence and watch it become text and tokens.", "Di una oración y mira cómo se vuelve texto y tokens."),
    "challenge.s8.c3.concept": ("Speech recognition turns sound into text.", "El reconocimiento de voz convierte el sonido en texto."),
    "challenge.s8.c4.title": ("Master of words", "Maestro de las palabras"),
    "challenge.s8.c4.goal": ("Have a short conversation with me and spot when I'm unsure.", "Ten una conversación corta conmigo y detecta cuándo no estoy seguro."),
    "challenge.s8.c4.concept": ("Models can sound sure and still be wrong.", "Los modelos pueden sonar seguros y aun así equivocarse."),

    # scenario 9
    "scenario.9.title": ("Fair Scale", "Balanza Justa"),
    "scenario.9.subtitle": ("Bias, fairness and privacy", "Sesgo, justicia y privacidad"),
    "scenario.9.concept": ("If the data is unfair, the AI is unfair. Good AI needs balanced data, privacy and people who check it.", "Si los datos son injustos, la IA es injusta. Una buena IA necesita datos balanceados, privacidad y personas que la revisen."),
    "scenario.9.intro": ("Something is wrong with this dataset: I only recognise black cats! Help me make it fair.", "Algo anda mal con estos datos: ¡solo reconozco gatos negros! Ayúdame a hacerlos justos."),
    "challenge.s9.c1.title": ("Only black cats", "Solo gatos negros"),
    "challenge.s9.c1.goal": ("Find out why I can't see orange cats.", "Descubre por qué no veo gatos naranjas."),
    "challenge.s9.c1.concept": ("Missing examples create bias.", "Los ejemplos que faltan crean sesgo."),
    "challenge.s9.c2.title": ("Balance the scale", "Equilibra la balanza"),
    "challenge.s9.c2.goal": ("Add examples until every kind of cat is represented.", "Agrega ejemplos hasta que todos los tipos de gato estén representados."),
    "challenge.s9.c2.concept": ("Balanced data is fairer data.", "Datos balanceados son datos más justos."),
    "challenge.s9.c3.title": ("Keep it private", "Mantenlo privado"),
    "challenge.s9.c3.goal": ("Choose which data an app should keep and which it should not.", "Elige qué datos debe guardar una app y cuáles no."),
    "challenge.s9.c3.concept": ("Private data stays with its owner.", "Los datos privados se quedan con su dueño."),
    "challenge.s9.c4.title": ("Master judge", "Maestro juez"),
    "challenge.s9.c4.goal": ("Review an AI decision and explain what went wrong.", "Revisa una decisión de IA y explica qué salió mal."),
    "challenge.s9.c4.concept": ("People must check AI decisions.", "Las personas deben revisar las decisiones de la IA."),

    # scenario 10
    "scenario.10.title": ("Creative Lab", "Laboratorio Creativo"),
    "scenario.10.subtitle": ("Generative AI and your project", "IA generativa y tu proyecto"),
    "scenario.10.concept": ("Generative AI makes new things from patterns it learned. You decide how to use it, and you take the credit!", "La IA generativa crea cosas nuevas a partir de patrones que aprendió. Tú decides cómo usarla, ¡y el mérito es tuyo!"),
    "scenario.10.intro": ("Final world! Let's create stories and ideas together, then build your own mini AI.", "¡Último mundo! Creemos historias e ideas juntos y luego construye tu propia mini IA."),
    "challenge.s10.c1.title": ("Story seeds", "Semillas de historia"),
    "challenge.s10.c1.goal": ("Give me three words and I'll grow a story. Change a word, change the story.", "Dame tres palabras y haré crecer una historia. Cambia una palabra, cambia la historia."),
    "challenge.s10.c1.concept": ("Generation follows the prompt.", "La generación sigue la instrucción."),
    "challenge.s10.c2.title": ("Remix", "Remezcla"),
    "challenge.s10.c2.goal": ("Remix my story so it is really yours.", "Remezcla mi historia para que sea realmente tuya."),
    "challenge.s10.c2.concept": ("Humans and AI create together.", "Humanos e IA crean juntos."),
    "challenge.s10.c3.title": ("Design a helper", "Diseña un ayudante"),
    "challenge.s10.c3.goal": ("Choose data, a goal and rules for your own helper AI.", "Elige datos, un objetivo y reglas para tu propia IA ayudante."),
    "challenge.s10.c3.concept": ("Every AI needs data, a goal and limits.", "Toda IA necesita datos, un objetivo y límites."),
    "challenge.s10.c4.title": ("Graduation", "Graduación"),
    "challenge.s10.c4.goal": ("Show everything you learned in one project.", "Muestra todo lo que aprendiste en un proyecto."),
    "challenge.s10.c4.concept": ("You understand AI. Keep asking how it works!", "Entiendes la IA. ¡Sigue preguntando cómo funciona!"),
})

# ---- game content vocabulary ------------------------------------------------
STRINGS.update({
    "fruit.attribute.color": ("colour", "color"),
    "fruit.attribute.shape": ("shape", "forma"),
    "fruit.attribute.size": ("size", "tamaño"),
    "fruit.color.red": ("red", "rojas"),
    "fruit.color.yellow": ("yellow", "amarillas"),
    "fruit.color.green": ("green", "verdes"),
    "fruit.color.purple": ("purple", "moradas"),
    "fruit.shape.round": ("round", "redondas"),
    "fruit.shape.long": ("long", "alargadas"),
    "fruit.size.small": ("small", "pequeñas"),
    "fruit.size.big": ("big", "grandes"),
    "basket.1": ("basket 1", "canasta 1"),
    "basket.2": ("basket 2", "canasta 2"),
    "basket.3": ("basket 3", "canasta 3"),
    "rule.value_to_basket": ("The %@ fruits go to basket %lld.", "Las frutas %@ van a la canasta %lld."),
    "rule.conjunction": ("Fruits that are %@ AND %@ go to basket %lld. The rest go to basket %lld.", "Las frutas %@ Y %@ van a la canasta %lld. Las demás van a la canasta %lld."),
    "rule.hidden": ("The rule is a secret. Try a fruit and watch the baskets glow.", "La regla es secreta. Prueba una fruta y mira cómo brillan las canastas."),
    "species.cat": ("cat", "gato"),
    "species.dog": ("dog", "perro"),
    "species.bird": ("bird", "ave"),
    "feature.size": ("size", "tamaño"),
    "feature.ears": ("pointy ears", "orejas puntiagudas"),
    "feature.song": ("song", "canto"),
})

# ---- AI CAT's script ---------------------------------------------------------
STRINGS.update({
    "dialog.greeting.1": ("Hi! I'm AI CAT. Ready to learn with me?", "¡Hola! Soy AI CAT. ¿Listo para aprender conmigo?"),
    "dialog.greeting.2": ("Meow! What shall we discover today?", "¡Miau! ¿Qué descubrimos hoy?"),
    "dialog.greeting.3": ("You're back! My tail is wagging with joy.", "¡Volviste! Mi cola se mueve de alegría."),
    "dialog.challenge_start.1": ("Let's try this one. Take your time.", "Probemos este. Tómate tu tiempo."),
    "dialog.challenge_start.2": ("A new challenge! I'm watching closely.", "¡Un reto nuevo! Observo con atención."),
    "dialog.master_intro.1": ("This is the master challenge. Fewer hints, more thinking!", "Este es el reto maestro. ¡Menos pistas, más pensar!"),
    "dialog.correct.1": ("Yes! That's right.", "¡Sí! Así es."),
    "dialog.correct.2": ("Purr-fect!", "¡Purr-fecto!"),
    "dialog.correct.3": ("I'm learning from you.", "Estoy aprendiendo de ti."),
    "dialog.correct.4": ("Great move!", "¡Gran jugada!"),
    "dialog.wrong.1": ("Hmm, not that one. Look again.", "Mmm, esa no. Mira otra vez."),
    "dialog.wrong.2": ("Almost! Try again.", "¡Casi! Intenta de nuevo."),
    "dialog.wrong.3": ("Mistakes help us learn. Try again!", "Los errores nos ayudan a aprender. ¡Otra vez!"),
    "dialog.hint.1": ("Here's a clue. Watch where this one goes.", "Aquí va una pista. Mira a dónde va esta."),
    "dialog.hint.2": ("Psst… let me show you one.", "Psst… déjame mostrarte una."),
    "dialog.ai_learned.1": ("I found the pattern! Let me sort the rest.", "¡Encontré el patrón! Déjame acomodar el resto."),
    "dialog.ai_learned.2": ("I think I understand the rule now!", "¡Creo que ya entiendo la regla!"),
    "dialog.ai_needs_more.1": ("I'm not sure yet. Show me more examples.", "Aún no estoy seguro. Muéstrame más ejemplos."),
    "dialog.ai_needs_more.2": ("Two rules could explain this. One more example, please!", "Dos reglas podrían explicarlo. ¡Un ejemplo más, por favor!"),
    "dialog.ai_sorted.1": ("Done! I sorted them using what you taught me.", "¡Listo! Los acomodé con lo que me enseñaste."),
    "dialog.challenge_complete.1": ("We did it! I feel bigger already.", "¡Lo logramos! Ya me siento más grande."),
    "dialog.challenge_complete.2": ("Challenge complete! High paw!", "¡Reto completado! ¡Choca esa pata!"),
    "dialog.challenge_complete.3": ("That was fun. What's next?", "Eso fue divertido. ¿Qué sigue?"),
    "dialog.scenario_complete.1": ("A whole world finished! Look what I earned.", "¡Un mundo completo! Mira lo que gané."),
    "dialog.scenario_complete.2": ("You taught me so much here. A new world is open!", "Me enseñaste mucho aquí. ¡Se abrió un mundo nuevo!"),
    "dialog.stage_up.1": ("Whoa, I grew! Thank you!", "¡Guau, crecí! ¡Gracias!"),
    "dialog.stage_up.2": ("Look at me, I'm bigger and smarter.", "Mírame, soy más grande y más listo."),
    "dialog.idle.1": ("Yawn… I'm here when you're ready.", "Bostezo… Aquí estoy cuando quieras."),
    "dialog.idle.2": ("What are you thinking?", "¿En qué piensas?"),
    "dialog.idle.3": ("I love this place.", "Me encanta este lugar."),
    "dialog.encouragement.1": ("You can do it!", "¡Tú puedes!"),
    "dialog.encouragement.2": ("Keep going, you're close.", "Sigue, estás cerca."),
    "dialog.encouragement.3": ("Every try makes us smarter.", "Cada intento nos hace más listos."),
    "dialog.locked.1": ("This world is still asleep. Finish the one before it.", "Este mundo aún duerme. Termina el anterior."),
    "dialog.trap_found.1": ("Wait… this label looks wrong. Something is confusing me!", "Espera… esta etiqueta parece incorrecta. ¡Algo me confunde!"),
    "dialog.s1.intro": ("Smell those fruits! Let's sort them.", "¡Huele esas frutas! Vamos a acomodarlas."),
    "dialog.s2.intro": ("So many cards! Help me label them.", "¡Cuántas tarjetas! Ayúdame a etiquetarlas."),
    "dialog.s3.intro": ("Time to build a sorting machine.", "Hora de construir una máquina que separa."),
    "dialog.s4.intro": ("Guide my paws with instructions!", "¡Guía mis patas con instrucciones!"),
    "dialog.s5.intro": ("A maze! Where are the treats?", "¡Un laberinto! ¿Dónde están los premios?"),
    "dialog.s6.intro": ("Welcome to my brain factory.", "Bienvenido a la fábrica de mi cerebro."),
    "dialog.s7.intro": ("Look through my eyes!", "¡Mira a través de mis ojos!"),
    "dialog.s8.intro": ("Let's play with words.", "Juguemos con palabras."),
    "dialog.s9.intro": ("Something isn't fair here. Help me fix it.", "Algo no es justo aquí. Ayúdame a arreglarlo."),
    "dialog.s10.intro": ("Let's create something new together!", "¡Creemos algo nuevo juntos!"),
})

# ---- app UI (M2) ------------------------------------------------------------
STRINGS.update({
    "onboarding.choose_language": ("Which language do you want to play in?", "¿En qué idioma quieres jugar?"),
    "onboarding.name_prompt": ("What is your kitten's name?", "¿Cómo se llama tu gatito?"),
    "onboarding.name_placeholder": ("AI CAT", "AI CAT"),
    "onboarding.ready_title": ("Ready to play?", "¿Listo para jugar?"),
    "onboarding.ready_adults": ("Adults: open the parent zone from the map (hold the paw) to choose the child's age and settings.", "Adultos: abran la zona de padres desde el mapa (mantener la pata) para elegir la edad y los ajustes."),
    "onboarding.start": ("Let's go!", "¡Vamos!"),
    "map.stage_format": ("Stage %lld of 10", "Etapa %lld de 10"),
    "map.xp_format": ("%lld XP · %lld more to grow", "%lld XP · %lld más para crecer"),
    "parent.zone": ("Parent zone", "Zona de padres"),
    "parent.gate_title": ("For adults", "Para adultos"),
    "parent.gate_hold": ("Press and hold the paw for two seconds.", "Mantén presionada la pata durante dos segundos."),
    "parent.gate_question": ("What is %lld + %lld?", "¿Cuánto es %lld + %lld?"),
    "parent.gate_wrong": ("Not quite. Try the new sum.", "No es correcto. Prueba con la nueva suma."),
    "parent.age_section": ("Child's age", "Edad del niño"),
    "parent.voice": ("AI CAT speaks aloud", "AI CAT habla en voz alta"),
    "parent.creative": ("Creative AI CAT (generated lines)", "AI CAT creativo (frases generadas)"),
    "parent.creative_footer": ("Uses Apple Intelligence on this device only, never the internet. Off by default: AI CAT always has a complete, pre-written script.", "Usa Apple Intelligence solo en este dispositivo, nunca internet. Apagado por defecto: AI CAT siempre tiene un guion completo escrito de antemano."),
    "parent.effects": ("Reduce effects and motion", "Reducir efectos y movimiento"),
    "parent.progress_section": ("Progress", "Progreso"),
    "parent.completed_format": ("%lld of 10 worlds completed", "%lld de 10 mundos completados"),
    "parent.reset": ("Reset progress", "Reiniciar progreso"),
    "parent.reset_confirm": ("Erase all progress? The kitten starts over.", "¿Borrar todo el progreso? El gatito empieza de nuevo."),
    "parent.privacy_section": ("Privacy", "Privacidad"),
    "parent.privacy_text": ("AI CAT works entirely on this device. It never connects to the internet, shows no ads, collects no data and asks for no personal information. The kitten's name and the progress are stored only on this device and can be erased above.", "AI CAT funciona completamente en este dispositivo. Nunca se conecta a internet, no muestra anuncios, no recopila datos ni pide información personal. El nombre del gatito y el progreso se guardan solo en este dispositivo y pueden borrarse arriba."),
    "parent.about": ("About", "Acerca de"),
    "parent.version_format": ("AI CAT version %@ · MIT license", "AI CAT versión %@ · licencia MIT"),
    "challenge.coming_soon_title": ("This workshop is still being built", "Este taller todavía se está construyendo"),
    "challenge.coming_soon_text": ("AI CAT is preparing this challenge. The first two worlds are ready to play!", "AI CAT está preparando este reto. ¡Los dos primeros mundos ya se pueden jugar!"),
    "challenge.goal_label": ("Goal", "Objetivo"),
    "challenge.concept_label": ("The idea", "La idea"),
    "result.title": ("Challenge complete!", "¡Reto completado!"),
    "result.try_again_title": ("Almost!", "¡Casi!"),
    "result.try_again_text": ("Let's try once more. AI CAT believes in you.", "Intentemos una vez más. AI CAT cree en ti."),
    "result.xp_format": ("+%lld XP", "+%lld XP"),
    "result.stage_up": ("AI CAT grew to stage %lld!", "¡AI CAT creció a la etapa %lld!"),
    "result.scenario_complete": ("World complete!", "¡Mundo completado!"),
    "result.knowledge_format": ("New: %@", "Nuevo: %@"),
    "result.next": ("Next challenge", "Siguiente reto"),
    "result.back": ("Back to the world", "Volver al mundo"),
    "result.again": ("Play again", "Jugar de nuevo"),
})
